#!/bin/sh

# Script which runs prettier on staged files right before commit is made
# Code copied from https://prettier.io/docs/en/precommit.html#option-6-shell-script

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Prettify all selected files
echo "$FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

# Run linter and block commit on errors
./node_modules/.bin/eslint src || exit 1

# Run typechecker and block commit on errors
./node_modules/.bin/tsc --noEmit || exit 1

exit 0
